### ISSUE TITLE
無料販売でも画像アップロードは対応してほしい

### ISSUE THREAD

**Issue by take-iwa** [MaruiorimonoTeam/cookle-web#168]
無料掲載の場合でも、画像をアップできるようにしてほしいです。
見た目が寂しい。

有料の場合の優遇は、表示場所と大きさということになります。

**Comment by take-iwa** [comment]
<img width="500" alt="airmaid" src="https://user-images.githubusercontent.com/23730555/30943810-70c8c522-a42e-11e7-9a93-30c36e8b0f62.png">

**Comment by take-iwa** [comment]
@alexeypolitov スマホ表示でも画像出るようお願いします、、すみません、
![1506558626931 jpeg](https://user-images.githubusercontent.com/23730555/30944615-1a7e3dd6-a434-11e7-8335-95d59bce9618.jpg)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
