### ISSUE TITLE
スマホ版で注文する際、日付や時間を入力しなくてもカード情報入力画面にいける

### ISSUE THREAD

**Issue by take-iwa** [MaruiorimonoTeam/cookle-web#171]
宮本さんが報告された件です。

PCでは「カードで支払う」を押した時点で未入力エラーが出ますが、
スマホだと「カードで支払う」を押すとカード情報入力画面が開ける。
　→情報入力するも日付などのに入力エラーが裏で出ているため、進めず

スマホでも「カードで支払う」を押した時点でに未入力チェックをかけて、
カード情報入力画面が開かないようにお願いします。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
