### ISSUE TITLE
購入者側、カートの住所入力部分でも住所と電話番号欄を違う段にしてほしい

### ISSUE THREAD

**Issue by take-iwa** [MaruiorimonoTeam/cookle-web#172]
販売者のサービス設定画面と同じように

![screenshot_20170928-144750](https://user-images.githubusercontent.com/23730555/30951242-d16ded48-a45c-11e7-9230-7cd8534651e1.png)

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
