### ISSUE TITLE
アンドロイド端末のchromeにて時刻入力した時、分の入力順がおかしい

### ISSUE THREAD

**Issue by take-iwa** [MaruiorimonoTeam/cookle-web#173]
購入時などに時間入力のときに

1030を入力するときに
30が03となります

**Comment by take-iwa** [comment]
@alexeypolitov 動画でアップします。
https://www.dropbox.com/s/mn6drp5mwpg7avk/2017_09_28_14_58_44.mp4?dl=0

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
